version: '3'

services:
  sqapi-loader:
    build: .
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi-loader
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2g
        reservations:
          cpus: '0.20'
          memory: 20M
      replicas: 1
    command: ['python', 'start.py', 'loader']

    volumes:
    - nifi-io:/io
    - sqapi-files:/opt/app/files
    - ../sqapi-plugins:/opt/sqapi/sqapi/plugins
    depends_on:
    - mq
    - redis
    - db


  sqapi-api:
    build: .
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2g
        reservations:
          cpus: '0.20'
          memory: 20M
      replicas: 2
    command: ['python', 'start.py', 'api']

    ports:
    - '5000:5000'
    volumes:
    - nifi-io:/io
    - sqapi-files:/opt/app/files
    - ../sqapi-plugins:/opt/sqapi/sqapi/plugins
    depends_on:
    - redis
    - db


  nifi:
    image: apache/nifi:${NIFI_V:-latest}
    container_name: nifi
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '8080:8080'
    volumes:
    - nifi-io:/io
    - nifi-conf:/opt/nifi/nifi-current/conf


  redis:
    image: redis:${REDIS_V:-latest}
    container_name: redis
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '6379:6379'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD", "bash", "-c", "exec", "3<>", "/dev/tcp/127.0.0.1/6379", "&&", "echo", "PING", ">&3", "&&", "head", "-1", "<&3", "|", "grep PONG"]


  mq:
    image: rabbitmq:${RABBIT_V:-latest}
    container_name: rabbit
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '5672:5672'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: [ "CMD", "rabbitmqctl", "status" ]


  db:
    image: postgres:${DB_V:-latest}
    container_name: postgres
    restart: unless-stopped
    user: "postgres:postgres"
    deploy:
      replicas: 1

    ports:
    - '5432:5432'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready", "--dbname=postgres", "--host=localhost", "--username=postgres"]


  es:
    image: elasticsearch:${ES_V:-7.3.0}
    container_name: elasticsearch
    restart: unless-stopped
    deploy:
      replicas: 1

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144

    environment:
    - 'discovery.type=single-node'
    ports:
    - '9200:9200'
    healthcheck:
      timeout: 5s
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]


volumes:
  nifi-io:
  nifi-conf:
  sqapi-files:
