version: '3'

services:
  nifi:
    image: apache/nifi:${NIFI_V:-latest}
    container_name: nifi
    restart: unless-stopped
    ports:
    - '8080:8080'

  redis:
    image: redis:${REDIS_V:-latest}
    container_name: redis
    restart: unless-stopped
    ports:
    - '6379:6379'

  mq:
    image: rabbitmq:${RABBIT_V:-latest}
    container_name: rabbit
    restart: unless-stopped
    ports:
    #- '5671:5671'
    - '5672:5672'

  sqapi:
    build: ./sqapi
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi
    restart: unless-stopped
    ports:
    - '5000:5000'

  db:
    image: postgres:{DB_V:-latest}
    container_name: postgres
    restart: unless-stopped
    ports:
    - ''

  web:
    build: ./web
    image: mabruras/sqapi-web
    container_name: web
    restart: unless-stopped
    ports:
    - '3000:3000'

