version: '3'

services:
  sqapi-loader:
    build: .
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi-loader
    restart: unless-stopped
    deploy:
      replicas: 1
    command: ['python', 'start.py', 'loader']
    environment:
    - 'PYTHONUNBUFFERED=1'

    volumes:
    - nifi-io:/io
    - sqapi-files:/opt/app/files
    depends_on:
    - mq
    - redis
    - db


  sqapi-api:
    build: .
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi-api
    restart: unless-stopped
    deploy:
      replicas: 2
    command: ['python', 'start.py', 'api']
    environment:
    - 'PYTHONUNBUFFERED=1'
    ports:
    - '5000:5000'

    volumes:
    - nifi-io:/io
    - sqapi-files:/opt/app/files
    depends_on:
    - redis
    - db


  nifi:
    image: apache/nifi:${NIFI_V:-latest}
    container_name: nifi
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
    - '8080:8080'

    volumes:
    - nifi-io:/io


  redis:
    image: redis:${REDIS_V:-latest}
    container_name: redis
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
    - '6379:6379'

    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD", "bash", "-c", "exec", "3<>", "/dev/tcp/127.0.0.1/6379", "&&", "echo", "PING", ">&3", "&&", "head", "-1", "<&3", "|", "grep PONG"]


  mq:
    image: rabbitmq:${RABBIT_V:-latest}
    container_name: rabbit
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
    - '5672:5672'

    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: [ "CMD", "rabbitmqctl", "status" ]


  db:
    image: postgres:${DB_V:-latest}
    container_name: postgres
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
    - '5432:5432'
    user: "postgres:postgres"

    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready", "--dbname=postgres", "--host=localhost", "--username=postgres"]


  # web:
  #   build: ./web
  #   image: mabruras/sqapi-web
  #   container_name: web
  #   restart: unless-stopped
  #   ports:
  #   - '3000:3000'

volumes:
  nifi-io:
  sqapi-files:
