version: '3.7'

services:
  sqapi:
    build: ../../..
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi
    restart: unless-stopped
    deploy:
      replicas: 2

    ports:
    - '5000:5000'
    volumes:
    - nifi-io:/io
    - sqapi-files:/opt/app/files
    - ./config.yml:/opt/mab/sqapi/resources/sqapi.yml:ro
    - ../../test/:/test/:ro


  nifi:
    image: apache/nifi:${NIFI_V:-latest}
    container_name: nifi
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '8080:8080'
    volumes:
    - nifi-io:/io
    - nifi-configuration:/opt/nifi/nifi-current/configuration


  redis:
    image: redis:${REDIS_V:-latest}
    container_name: redis
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '6379:6379'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD", "bash", "-c", "exec", "3<>", "/dev/tcp/127.0.0.1/6379", "&&", "echo", "PING", ">&3", "&&", "head", "-1", "<&3", "|", "grep PONG"]


  mq:
    image: rabbitmq:${RABBIT_V:-latest}
    container_name: rabbit
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '5672:5672'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: [ "CMD", "rabbitmqctl", "status" ]


  db:
    image: postgres:${DB_V:-latest}
    container_name: postgres
    restart: unless-stopped
    user: "postgres:postgres"
    deploy:
      replicas: 1

    ports:
    - '5432:5432'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready", "--dbname=postgres", "--host=localhost", "--username=postgres"]


volumes:
  nifi-io:
  nifi-conf:
  sqapi-files:
