version: '3'

services:
  sqapi-api:
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi-api
    restart: unless-stopped

    ports:
    - '5000:5000'
    volumes:
    - sqapi-files:/opt/app/files
    command: ['python', 'start.py', 'api']


  sqapi-loader:
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi-loader
    restart: unless-stopped

    volumes:
    - sqapi-files:/opt/app/files
    command: ['python', 'start.py', 'loader']


  db:
    image: postgres:${DB_V:-latest}
    container_name: postgres
    restart: unless-stopped
    user: "postgres:postgres"

    volumes:
    - db-content:/var/lib/postgresql/content
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready", "--dbname=postgres", "--host=localhost", "--username=postgres"]


volumes:
  sqapi-files:
  db-data:
