packages:
  install: False

broker:
  type: 'kafka'
  host: 'kafka'
  port: 29092  # Only for docker network internals, use port 9092 for host machine connections

  retry_interval: 0
  process_delay: 0

  # Note: Define either subscription_pattern OR topic_names - Not both!
  # subscription_pattern: '^.*$'
  topic_names:
  - 'sqapi'
  consumer_group: 'sqapi'
  api_version: [ 0, 10, 0 ]

message:
  parser:
    type: json

  fields:
    type:
      key: 'data_type'
      required: True
    data_location:
      key: 'data_path'
      required: True
    meta_location:
      key: 'meta_path'
      required: True
    uuid:
      key: 'uuid'
      required: True
    metadata:
      key: 'metadata'
      required: False

database:
  type: 'postgres'
  init: 'scripts/init.sql'
  connection:
    name: 'postgres'
    port: '5432'
    user: 'postgres'
    host: 'db'
    password: 'postgres'
    timeout: 2

data_store:
  type: 'disk'
