packages:
  install: False

msg_broker:
  type: 'zeromq'
  host: '*'
  port: 5001
  retry_interval: 0
  process_delay: 0
  connection_type: bind
  socket_type: 7
  protocol: 'tcp'

  parser: 'string'
  format: 'uuid|file|metadata'
  delimiter: '|'

  mime:
    path: 'mime.type'
    path_separator: '_'

  message_fields:
    uuid:
      key: 'uuid'
      required: True
    data_location:
      key: 'file'
      required: True
    meta_location:
      key: 'uuid'
      required: True
    metadata:
      key: 'metadata'
      required: False

database:
  type: 'postgres'
  init: 'scripts/init.sql'
  connection:
    name: 'postgres'
    port: '5432'
    user: 'postgres'
    host: 'db'
    password: 'postgres'
    timeout: 2

data_store:
  type: 'disk'
