version: '3.7'

services:
  sqapi:
    image: mabruras/sqapi:${SQAPI_V:-latest}
    container_name: sqapi
    restart: unless-stopped
    deploy:
      replicas: 1

    ports:
    - '5000:5000'
    - '5001:5001'
    volumes:
    - sqapi-files:/opt/app/files
    - ./config.yml:/opt/mab/sqapi/resources/sqapi.yml:ro
    - ../../test/:/test/:ro


  db:
    image: postgres:${DB_V:-latest}
    container_name: postgres
    restart: unless-stopped
    user: "postgres:postgres"
    deploy:
      replicas: 1

    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready", "--dbname=postgres", "--host=localhost", "--username=postgres"]


volumes:
  sqapi-files:
